In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("data.csv")

In [4]:
df.head(10)

,Invoice_ID,Age,Gender,Product_Category,Unit_Price,Quantity,Total_Amount,City
0,1001,25.0,Male,Electronics,500.0,1.0,500,Kathmandu
1,1002,30.0,Female,Clothing,50.0,2.0,100,Pokhara
2,1003,22.0,NaN,Groceries,20.0,5.0,100,Lalitpur
3,1004,28.0,Male,Electronics,NaN,1.0,500,Kathmandu
4,1005,35.0,Female,Clothing,60.0,NaN,120,NaN
5,1006,40.0,Male,Groceries,15.0,10.0,150,Bhaktapur
6,1007,29.0,Female,Electronics,700.0,1.0,700,Kathmandu
7,1008,31.0,Male,Clothing,80.0,2.0,160,Pokhara
8,1009,NaN,Female,Groceries,25.0,4.0,100,Lalitpur
9,1010,45.0,Male,Electronics,1000.0,1.0,1000,Kathmandu

In [7]:
df.shape

(50, 8)

In [5]:
df.describe()

       Invoice_ID        Age   Unit_Price   Quantity  Total_Amount
count    50.00000  49.000000    49.000000  49.000000     50.000000
mean   1025.50000  32.795918   371.857143   2.877551    430.960000
std      14.57738   6.822083   758.394604   2.185489    726.571849
min    1001.00000  21.000000    15.000000   1.000000     85.000000
25%    1013.25000  28.000000    24.000000   1.000000    127.000000
50%    1025.50000  32.000000    75.000000   2.000000    162.500000
75%    1037.75000  37.000000   550.000000   5.000000    540.000000
max    1050.00000  50.000000  5000.000000  10.000000   5000.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Invoice_ID        50 non-null     int64
 1   Age               49 non-null     float64
 2   Gender            49 non-null     object
 3   Product_Category  50 non-null     object
 4   Unit_Price        49 non-null     float64
 5   Quantity          49 non-null     float64
 6   Total_Amount      50 non-null     int64
 7   City              49 non-null     object
dtypes: float64(3), int64(2), object(3)
memory usage: 3.3+ KB

In [9]:
df.isnull().sum()

Invoice_ID          0
Age                 1
Gender              1
Product_Category    0
Unit_Price          1
Quantity            1
Total_Amount        0
City                1
dtype: int64

In [22]:
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
df['Unit_Price'].fillna(df['Unit_Price'].median(), inplace=True)
df['City'].fillna("Unknown", inplace=True)
df['Quantity'].fillna(df['Quantity'].median(), inplace=True)

In [23]:
df.isnull().sum()

Invoice_ID          0
Age                 0
Gender              0
Product_Category    0
Unit_Price          0
Quantity            0
Total_Amount        0
City                0
dtype: int64

In [26]:
print(df[df.duplicated(keep=False)])

Empty DataFrame
Columns: [Invoice_ID, Age, Gender, Product_Category, Unit_Price, Quantity, Total_Amount, City]
Index: []

In [27]:
df.drop_duplicates(inplace=True)

In [34]:
numerical_cols = df.select_dtypes(include=['number']).columns
for col in numerical_cols:
    try:
        df[col] = pd.to_numeric(df[col], errors='ignore')
    except:
        pass

C:\Users\USER\AppData\Local\Temp\ipykernel_9632\2276309122.py:4: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')

In [29]:
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    df[col] = df[col].str.strip().str.lower()

df.to_csv('data.csv', index=False)

In [35]:
df.head()

,Invoice_ID,Age,Gender,Product_Category,Unit_Price,Quantity,Total_Amount,City
0,1001,25.0,male,electronics,500.0,1.0,500,kathmandu
1,1002,30.0,female,clothing,50.0,2.0,100,pokhara
2,1003,22.0,male,groceries,20.0,5.0,100,lalitpur
3,1004,28.0,male,electronics,75.0,1.0,500,kathmandu
4,1005,35.0,female,clothing,60.0,2.0,120,unknown

In [40]:
cols=['Age', 'Unit_Price', 'Total_Amount']

for col in cols:
    mean=df[col].mean()
    median=df[col].median()
    diff = abs(mean-median)

    mode=df[col].mode()[0]

    print(f"Mean of {col}:{mean} Median of {col}:{median} Mode of {col}:{mode}")
    
    if diff > 0:
        print(f"{col} is skewed.")
    elif diff< 0:
        print(f"{col} is not skewed.")
    else:
        print(f"{col} is perfectly symmetric.")

    print("\n")

Mean of Age:32.79591836734694 Median of Age:32.397959183673464 Mode of Age:29.0
Age is skewed.


Mean of Unit_Price:365.92 Median of Unit_Price:75.0 Mode of Unit_Price:18.0
Unit_Price is skewed.


Mean of Total_Amount:430.96 Median of Total_Amount:162.5 Mode of Total_Amount:100
Total_Amount is skewed.

In [42]:
cols=['Age', 'Unit_Price', 'Total_Amount']

for col in cols:
    q1= df[col].quantile(0.25)
    q3= df[col].quantile(0.75)  

    irq=q3-q1

    lower_bound=q1-1.5*irq
    upper_bound=q3+1.5*irq

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    print(f"Outliers in {col}:\n{outliers}\n")

    # df=df[df[col>=lower_bound] & df[col]<=upper_bound ]

    df[col] = df[col].clip(lower_bound, upper_bound)

Outliers in Age:
Empty DataFrame
Columns: [Invoice_ID, Age, Gender, Product_Category, Unit_Price, Quantity, Total_Amount, City]
Index: []

Outliers in Unit_Price:
    Invoice_ID   Age Gender Product_Category  Unit_Price  Quantity  \
49        1050  50.0   male      electronics      5000.0       1.0

    Total_Amount       City
49          5000  kathmandu

Outliers in Total_Amount:
    Invoice_ID   Age Gender Product_Category  Unit_Price  Quantity  \
27        1028  44.0   male      electronics    1200.000       1.0
49        1050  50.0   male      electronics    1313.625       1.0

    Total_Amount       City
27          1200  kathmandu
49          5000  kathmandu

In [44]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [46]:

df[["Unit_Price","Quantity","Total_Amount"]] = MinMaxScaler().fit_transform(df[["Unit_Price","Quantity","Total_Amount"]])
df['Age'] = StandardScaler().fit_transform(df[['Age']])

In [49]:
df = pd.get_dummies(df, columns=['Gender', 'Product_Category', 'City'], drop_first=True)

In [51]:
df.head()

,Invoice_ID,Age,Unit_Price,Quantity,Total_Amount,Gender_male,Product_Category_electronics,Product_Category_groceries,City_kathmandu,City_lalitpur,City_pokhara,City_unknown
0,1001,-1.166312,0.373472,0.000000,0.386226,True,True,False,True,False,False,False
1,1002,-0.418285,0.026952,0.111111,0.013960,False,False,False,False,False,True,False
2,1003,-1.615128,0.003850,0.444444,0.013960,True,False,True,False,True,False,False
3,1004,-0.717495,0.046203,0.000000,0.386226,True,True,False,True,False,False,False
4,1005,0.329743,0.034652,0.111111,0.032573,False,False,False,False,False,False,True